# Unit in [um]
Pad:
  layer: 1
  width: 250
  height: 400
  rounding: 20
  gap: 20 # gap between two capacitance pads

JJ:
  finger:
    layer: 1
    up:
      length: 10.0
      width: 0.2
    down:
      length: 10.0
      width: 1.0
    # For dolan structure, JJ size will be affected by rounding, so this should be 0
    rounding: 0
  pad_box:
    width: 2.0
    length: 10
    gap: 4.0
  bridge:
    width: 0.9
  taper:
    width1: 10
    width2: 40
    length: 100
    gap: 10

Pad_JJ:
  rounding: 0

DicingMarker:
  layer: 1
  width: 100
  # length: 400
  length: 1600

Chip:
  size:
    x: 1000
    y: 2000

Grid:
  pad_size: ['S', 'S', 'S', 'S']

  finger_width: 
    - [0.5, 0.6, 0.7, 0.8, 0.9]
    - [1.0, 1.1, 1.2, 1.3, 1.4]
       
  finger_height: # this is actually bridge_width...
    - [0.7, 0.8, 0.9]
    - [0.7, 0.8, 0.9]
    - [0.7, 0.8, 0.9]
    - [0.7, 0.8, 0.9]
 
  gap:
    x: 1
    y: 1

Text:
  string: '"fw " + str(width) + "\nbw " + str(height)'
  pos:
    x: -0.8
    y: -0.85