name: Test Notebooks

on: [push, pull_request]

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          channel-priority: strict
          auto-update-conda: true
          python-version: 3.11
          auto-activate-base: false
          activate-environment: phidl

      - name: Install dependencies
        run: |
          conda install -y phidl
          conda install -y matplotlib
          conda install -y pyyaml
          conda install -y scipy

      - name: Install Jupyter tools
        run: |
          conda install -y jupyter nbconvert

      - name: Install test deps
        run: |
          pip install pytest nbmake

      - name: Run notebook tests
        run: |
          pytest --nbmake $(find . -name "*.ipynb")